[package]
name = 'kit'
version = '3.0.0'
authors = ['Brandon Macer <bobbysox322@gmail.com>']
edition = '2018'

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
frame-system = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
]

 method cannot be called on `_::_parity_scale_codec::Error` due to unsatisfied trait bounds